import type { Metadata } from 'next'
import { Bebas_Neue, Space_Mono } from 'next/font/google'
import '@mdxrenderdocs/ui/globals.css'

const bebas = Bebas_Neue({
  variable: '--font-bebas',
  subsets: ['latin'],
  weight: '400',
})
const spaceMono = Space_Mono({
  variable: '--font-space-mono',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'mdxRenderDocs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="pt-BR">
      <body className={`${bebas.variable} ${spaceMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
